### ISSUE TITLE
什么时候开源？

### ISSUE THREAD

**Issue by shinebay** [Aechoterm/Aechoterm#1]
不开源的ssh客户端，谁敢用？

**Comment by JustTestCode** [comment]
确实,不开源的都是公司,口碑很久了的,
纯个人不开源,不敢用

**Comment by Aechoterm** [comment]
我们本身是it行业，软件是我们公司自己开发自己用的，不是什么大项目，所以免费分享出来，也是为了收集一些好的意见，更好迭代优化，目前没有开源的打算。

**Comment by helloxz** [comment]
> 我们本身是it行业，软件是我们公司自己开发自己用的，不是什么大项目，所以免费分享出来，也是为了收集一些好的意见，更好迭代优化，目前没有开源的打算。

感谢您的解答，软件其实挺好用的，吊打市面上很多收费软件。我有一些个人建议：
1. 让用户可以自行选择同步数据，这样可以打消部分用户安全的疑虑
2. 可以分享一些技术干货，比如加密保存的一些知识
3. 可以适当收取一定的费用，从而保障软件良性发展

**Comment by Aechoterm** [comment]
> > 我们本身是it行业，软件是我们公司自己开发自己用的，不是什么大项目，所以免费分享出来，也是为了收集一些好的意见，更好迭代优化，目前没有开源的打算。
> 
> 感谢您的解答，软件其实挺好用的，吊打市面上很多收费软件。我有一些个人建议：
> 
> 1. 让用户可以自行选择同步数据，这样可以打消部分用户安全的疑虑
> 2. 可以分享一些技术干货，比如加密保存的一些知识
> 3. 可以适当收取一定的费用，从而保障软件良性发展

**Comment by Aechoterm** [comment]
> > 我们本身是it行业，软件是我们公司自己开发自己用的，不是什么大项目，所以免费分享出来，也是为了收集一些好的意见，更好迭代优化，目前没有开源的打算。
> 
> 感谢您的解答，软件其实挺好用的，吊打市面上很多收费软件。我有一些个人建议：
> 
> 1. 让用户可以自行选择同步数据，这样可以打消部分用户安全的疑虑
> 2. 可以分享一些技术干货，比如加密保存的一些知识
> 3. 可以适当收取一定的费用，从而保障软件良性发展



> > 我们本身是it行业，软件是我们公司自己开发自己用的，不是什么大项目，所以免费分享出来，也是为了收集一些好的意见，更好迭代优化，目前没有开源的打算。
> 
> 感谢您的解答，软件其实挺好用的，吊打市面上很多收费软件。我有一些个人建议：
> 
> 1. 让用户可以自行选择同步数据，这样可以打消部分用户安全的疑虑
> 2. 可以分享一些技术干货，比如加密保存的一些知识
> 3. 可以适当收取一定的费用，从而保障软件良性发展

非常感谢您的建议，开发这个软件主要是由于版权问题，首先是为了保证内部人员的使用，所以一直没有做收费的规划，但是随着用户的增多，在服务器各方面的资金投入肯定会有一些负担，未来会有收费的打算。

关于安全性问题，我们也比较重视，主要是涉及云同步的内容，可能用户会有担忧。目前4.0.0版本已经做了一些优化，包括自动云同步设定，以及密码、自定义密钥的多重认证。
“分享加密保存的一些知识”，这点我非常认同，3.0.3版本在创建会话、云同步等页面都有进行相关的提示，后续会考虑做一个专题。

安全性有时候很难用言语去保证，获取用户的会话信息，对我们来说毫无用处，甚至会触犯法律，哪个正规的公司会这样做呢。
抛开公司立场，我个人认为，ssh工具很多，如果真的担心可以选择自己认为安全一些的。
开发不易，我们接受合理的质疑，也欢迎热心的建议。但我们只能做力所能及之事，在有限的精力和财力内。
再次感谢您的建议。

**Comment by logoove** [comment]
这工具就是完美的 用了下windterm nsxhell都有bug,还没人修复,这个完全没有,

**Comment by helloxz** [comment]
> 这工具就是完美的 用了下windterm nsxhell都有bug,还没人修复,这个完全没有,

不是你想象中的那么美好，比如这个BUG：https://github.com/Aechoterm/Aechoterm/issues/3
